# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pilot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.CharField(max_length=20)),
                ('host', models.CharField(max_length=40)),
                ('ts_reg', models.DateTimeField(auto_now=True, verbose_name='ts_def')),
            ],
        ),
    ]
