# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pilot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default='', max_length=36)),
                ('j_uuid', models.CharField(default='', max_length=36)),
                ('jpid', models.CharField(default='', max_length=16)),
                ('state', models.CharField(default='', max_length=16)),
                ('status', models.CharField(default='', max_length=16)),
                ('site', models.CharField(default='', max_length=32)),
                ('host', models.CharField(default='', max_length=32)),
                ('ts_cre', models.DateTimeField(blank=True, null=True, verbose_name='ts_cre')),
                ('ts_reg', models.DateTimeField(blank=True, null=True, verbose_name='ts_reg')),
                ('ts_lhb', models.DateTimeField(blank=True, null=True, verbose_name='ts_lhb')),
                ('jobcount', models.PositiveIntegerField(default=0)),
                ('jobs_done', models.TextField(default='')),
                ('pid', models.CharField(default='', max_length=16)),
            ],
        ),
    ]
