# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-10 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilot',
            name='extra',
            field=models.CharField(default='', max_length=256),
        ),
    ]
