# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-14 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
                ('ts', models.DateTimeField(blank=True, null=True, verbose_name='ts')),
                ('info', models.TextField(default='')),
            ],
        ),
    ]
