# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-03 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dag',
            fields=[
                ('name', models.CharField(default='', max_length=64, primary_key=True, serialize=False)),
                ('user', models.CharField(default='', max_length=64)),
                ('description', models.TextField(default='')),
                ('nvertices', models.IntegerField(default=0)),
                ('root', models.CharField(default='', max_length=64)),
                ('ts_def', models.DateTimeField(blank=True, null=True, verbose_name='ts_def')),
            ],
        ),
        migrations.CreateModel(
            name='dagEdge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dag', models.CharField(default='', max_length=64)),
                ('name', models.CharField(default='', max_length=64)),
                ('dirpath', models.CharField(default='', max_length=256)),
                ('comment', models.CharField(default='', max_length=256)),
                ('datatype', models.CharField(default='', max_length=64)),
                ('datatag', models.CharField(default='', max_length=64)),
                ('source', models.CharField(default='', max_length=64)),
                ('target', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='dagVertex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('dag', models.CharField(default='', max_length=64)),
                ('jobtype', models.CharField(default='', max_length=16)),
                ('payload', models.CharField(default='', max_length=256)),
                ('env', models.TextField(default='{}')),
                ('timelimit', models.PositiveIntegerField(default=1000)),
                ('priority', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default='', max_length=36)),
                ('user', models.CharField(default='', max_length=64)),
                ('comment', models.TextField(default='')),
                ('rootuuid', models.CharField(default='', max_length=36)),
                ('name', models.CharField(default='', max_length=64)),
                ('description', models.TextField(default='')),
                ('dag', models.CharField(default='', max_length=64)),
                ('state', models.CharField(default='', max_length=16)),
                ('ts_def', models.DateTimeField(blank=True, null=True, verbose_name='ts_def')),
                ('ts_sta', models.DateTimeField(blank=True, null=True, verbose_name='ts_sta')),
                ('ts_sto', models.DateTimeField(blank=True, null=True, verbose_name='ts_sto')),
                ('nvertices', models.IntegerField(default=0)),
                ('ndone', models.IntegerField(default=0)),
            ],
        ),
    ]
