# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default='', max_length=36)),
                ('user', models.CharField(default='', max_length=64)),
                ('name', models.CharField(default='', max_length=64)),
                ('p_uuid', models.CharField(default='', max_length=36)),
                ('wfuuid', models.CharField(default='', max_length=36)),
                ('jobtype', models.CharField(default='', max_length=16)),
                ('payload', models.CharField(default='', max_length=256)),
                ('params', models.CharField(default='', max_length=256)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('timelimit', models.PositiveIntegerField(default=1000)),
                ('state', models.CharField(default='', max_length=16)),
                ('ts_def', models.DateTimeField(blank=True, null=True, verbose_name='ts_def')),
                ('ts_dis', models.DateTimeField(blank=True, null=True, verbose_name='ts_dis')),
                ('ts_sta', models.DateTimeField(blank=True, null=True, verbose_name='ts_sta')),
                ('ts_sto', models.DateTimeField(blank=True, null=True, verbose_name='ts_sto')),
                ('env', models.TextField(default='{}')),
                ('pid', models.CharField(default='', max_length=16)),
                ('errcode', models.CharField(default='', max_length=16)),
                ('directive', models.CharField(default='', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='jobtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('njobs', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='prioritypolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
                ('value', models.CharField(default='', max_length=32)),
            ],
        ),
    ]
