# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='ts_dispatch',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ts_dispatch'),
        ),
        migrations.AddField(
            model_name='job',
            name='ts_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ts_start'),
        ),
        migrations.AddField(
            model_name='job',
            name='ts_stop',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ts_stop'),
        ),
        migrations.AlterField(
            model_name='job',
            name='ts_def',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ts_def'),
        ),
    ]
