# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-29 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='site',
            fields=[
                ('name', models.CharField(default='', max_length=64, primary_key=True, serialize=False)),
                ('env', models.TextField(default='{}')),
                ('server', models.CharField(default='', max_length=64)),
                ('pilotcycles', models.PositiveIntegerField(default=1)),
                ('pilotperiod', models.PositiveIntegerField(default=5)),
            ],
        ),
    ]
