# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-01 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='pilotbeat',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='site',
            name='pilotperiod',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
